name: regradocorte_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:

  http: 1.1.2
  line_icons: ^2.0.2
  geolocator: ^10.1.0
  geocoding: ^2.0.1
  google_nav_bar: ^5.0.6
  syncfusion_flutter_calendar: ^24.1.45
  video_player: ^2.4.0
  flare_flutter: ^3.0.0
  
dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1

  mobx_codegen: ^2.1.1
  objectbox_generator: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon.png"
 
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  